### PR TITLE
adding make a globe code and merge into video scripts

### PR DESCRIPTION
**Pull request by sarawebb**
Using Ipython notebook to genarate globe images, to add background use the add_background script and save new images. To create video use the make_globe_video and change frame rate etc.

This PR was made under duress of Jacob.

### CODE REVIEW

**Comment by jacobseiler** [comment]
Could you add some comments to `add_background_image.py` and `make_globe_video.py` to explain exactly what's happening?  Like a header for each file that says 'This function does...' and some inline comments? 

If you make and push changes to your fork (i.e., `git push origin master` once you've added and committed the changes) they'll sync correctly here.

**Comment by sarawebb** [comment]
Sure can :)

**Comment by sarawebb** [comment]
Pushed :)

**Comment by jacobseiler** [comment]
Thanks Sara, looks great! 

@manodeep Feel free to merge + close when you're happy.

**Comment by manodeep** [comment]
Will it be possible to add a link to a movie demonstrating what the script does? (I heard really good things about it :) )

**Comment by sarawebb** [comment]
Hey Mandodeep!

I just added and pushed the DWF video onto git for people to download and
have a look at. Hope thats okay! :)
Can we also link back to Adams original notebook that hasn't been changed
for DWF so people can start from scratch to make any globe videos they want
which is pretty cool!

Thanks,
Sara :)

**Comment by jacobseiler** [comment]
Hey @sarawebb , you should be able to tag Github usernames in your commit message with @Username (so @abatten should tag Adam).  

You could link to Adam's notebook by copying the URL of his Github repo with the code and putting it in the header of your own files.  "Code is based on..."

**Comment by sarawebb** [comment]
Done! :)

**Comment by manodeep** [comment]
Thanks @sarawebb! 

Do you mind replacing the mp4 with a gif? Then the movie will render in the browser. If the file size becomes too big then ( > 5 MB), then we might stick the gif on an external link and include the link here.

**Comment by sarawebb** [comment]
gif is too big to upload to the git but I have it I can give to you at some point ? The video will also be going on the DWF website so we can point to that when it does too :)

**Comment by manodeep** [comment]
Thanks @sarawebb! Merging in then.

**Pull request merged**
