### PR TITLE
Added extract.sh for decompressing most files

### PR DESCRIPTION
**Pull request by abatten**
Extract.sh is this function I found online that I have added to my bashrc. It could be of use to some people.

### CODE REVIEW

**Comment by manodeep** [comment]
Is it possible to make this into a bash function, put that function into `.bashrc` or `.bash_profile`?

**Comment by abatten** [comment]
I have changed it to a bash script to be added to `.bashrc` or `.bash_profile`

**Comment by manodeep** [comment]
I should have asked - you checked that the copy-pasting that `extract` function into your `.bashrc` works as expected - yeah?

**Comment by abatten** [comment]
Yeah. I basically just copied the function from my .bashrc into that file. I have tested it and it still works.

**Pull request merged**
